project:
  type: default

format:
  revealjs:
    theme: [simple, custom.scss]
    logo: images/logo.png
    css: animation_styles.css
    slide-number: true
    toc: true

execute:
  echo: true

render:
  - presentations/session-1-lme4.qmd
  - presentations/session-2-brms.qmd
